name: assignment
description: A new Flutter application.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_custom_clippers: ^1.1.2
  carousel_pro: ^0.0.1
  flutter_native_image: ^0.0.6
  image_cropper: ^1.0.2
  flutter_image_compress: ^0.6.0
  google_fonts: any
  firebase_auth: ^0.18.0+1
  firebase_auth_web: any
  cloud_firestore: ^0.14.0+2
  cloud_firestore_web: any
  google_sign_in: ^4.5.3
  transparent_image: ^2.0.0
  shared_preferences: ^0.5.11
  fluttertoast: ^7.1.1
  image_picker: ^0.6.7+11
  email_validator: 2.0.1
  cached_network_image: ^2.3.2+1
  intl: ^0.16.1
  firebase_database: ^4.0.0
  firebase_storage : ^4.0.0
  uuid: ^2.2.2
  flutter_typeahead: ^1.8.8
  flutter_launcher_icons: ^0.8.1
  provider: ^5.0.0

#  google_fonts: ^2.1.0
#  cloud_firestore: ^2.2.0
#  firebase_auth: ^1.2.0
#  firebase_storage: ^8.1.3
#  firebase_core: ^1.2.1
#  firebase_analytics: ^8.1.1
#  razorpay_flutter: ^1.2.6
#  toast: ^0.1.5
#  fluttertoast: ^8.0.6
#  email_validator: ^2.0.1
#  image_picker: ^0.8.0+4
#
#  carousel_pro: ^0.0.1
#  cached_network_image: ^2.3.2+1


dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:
  uses-material-design: true

  assets:
       - assets/images/
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
